#!/bin/sh
export HOME=/home
docker run  --rm \
  --init \
  -e DISPLAY \
  -e XAUTHORITY \
  -v ssh:/home/.ssh \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -v "$XAUTHORITY:/root/.Xauthority:rw" \
  --hostname workstation \
  -u $ID:997 \
  -e HOME \
  -v minpac:/home/.vim/pack/minpac \
  -v /home/stan/Projects:/app \
  -p 3000:3000 \
  workstation
  #--entrypoint /bin/zsh -it workstation
  #-v $(pwd):/app \
  #--net=host \
  #-w /app \
